spring:
  jta:
    atomikos:
      datasource:
        primary:
          xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
          xaProperties:
            url: jdbc:mysql://localhost:3306/db_01
            user: root
            password: 123456
        secondary:
          xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
          xaProperties:
            url: jdbc:mysql://localhost:3306/db_02
            user: root
            password: 123456